image: digitalautonomy/wahay:0.2-build

stages:
  - build
  - check
  - deploy

build-oldest:
  image: digitalautonomy/wahay:0.4-build-oldest-golang
  stage: build
  script:
    - make deps-ci
    - make build-ci

build-newest:
  image: digitalautonomy/wahay:0.4-build-latest-golang
  stage: build
  script:
    - make deps-ci
    - make build-ci
  artifacts:
    paths:
      - bin/wahay-*

test-oldest:
  image: digitalautonomy/wahay:0.4-check-oldest-golang
  stage: check
  script:
    - make deps-ci
    - make test

test-newest:
  image: digitalautonomy/wahay:0.4-check-latest-golang
  stage: check
  script:
    - make deps-ci
    - make test

# coverage:
#   stage: check
#   coverage: '/total:.*?(\d+\.\d+\%)/'
#   script:
#     - make deps-ci
#     - make cover-ci
#   artifacts:
#     paths:
#       - coverage.html

# quality:
#   stage: check
#   script:
#     - make deps-ci
#     - make quality

deploy_staging:
  image: digitalautonomy/wahay:0.1-deploy
  stage: deploy
  before_script:
  - export SSH_PORT=2326
  - 'export DO_SSH="ssh -p${SSH_PORT} wahay@staging.wahay.app"'
  - 'eval $(ssh-agent -s)'
  - 'ssh-add <(echo "$DEPLOY_STAGING_SSH_PRIVATE_KEY")'
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - 'echo -e "[staging.wahay.app]:${SSH_PORT},[185.108.76.88]:${SSH_PORT} ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEiKOqqE2wJo4OnAvgbCPLsnObcSJuoYQU0cW3QRMPqK4XHeo9RTxOE4jt+40Gy3wfzzo7q1fmUJ/QZrORcNI6Y=" >> ~/.ssh/known_hosts'
  - 'echo -e "[debian.autonomia.digital]:4242,[185.108.78.22]:4242 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIx8qF3puSAM1UAxc3ODJTNGrgwf8mET664pPfP/ZQgiMxTIKG8Ar8h1xxP52AyQoqTLpCWOPaBkUya2Q0+SZTg=" >> ~/.ssh/known_hosts'
  - chmod 644 ~/.ssh/known_hosts
  - 'echo "$GPG_SIGNING_SUBKEY" | gpg --batch --import'
  - 'ssh-add <(echo "$ARTIFACTS_REPO_SSH_PRIVATE_KEY")'
  - mkdir tmp_bundle
  - "scp -P4242 'artifact-repo@debian.autonomia.digital:wahay/bundles/*' tmp_bundle/"
  environment:
    name: staging
    url: https://staging.wahay.app
  only:
    - main
  script:
   - 'export DEPLOY_DIR=/home/wahay/tmp/deploy_binaries'
   - '$DO_SSH rm -rf $DEPLOY_DIR'
   - '$DO_SSH mkdir -p $DEPLOY_DIR'
   - 'export BINARY_NAME=$(find bin -name "wahay-*" | head -1)'
   - 'sha256sum $BINARY_NAME > $BINARY_NAME.sha256sum'
   - 'gpg --batch --detach-sign --armor -u 3EE89711B35F8B3089646FCBF3B1159FC97D5490 $BINARY_NAME.sha256sum'
   - 'deployment/create-bundles.sh'
   - 'scp -P${SSH_PORT} $BINARY_NAME $BINARY_NAME.sha256sum $BINARY_NAME.sha256sum.asc publish-bundles/* wahay@staging.wahay.app:$DEPLOY_DIR/'
   - 'scp -P${SSH_PORT} deployment/*.{sh,rb,html} wahay@staging.wahay.app:bin/'
   - 'scp -P${SSH_PORT} deployment/supported-*-distros.txt wahay@staging.wahay.app:$DEPLOY_DIR'
   - '$DO_SSH bash bin/publish-downloads.sh $DEPLOY_DIR /usr/local/www/wahay/downloads $DEPLOY_DIR/$(basename $BINARY_NAME)'
   - '$DO_SSH "ruby bin/generate-downloads-html.rb /usr/local/www/wahay/downloads $DEPLOY_DIR > /usr/local/www/wahay/downloads.html"'

# TODO: FIX PRODUCTION DEPLOY!
deploy_production:
  image: digitalautonomy/wahay:0.1-deploy
  stage: deploy
  before_script:
  - export SSH_PORT=2387
  - 'export DO_SSH="ssh -p${SSH_PORT} wahay@wahay.app"'
  - "eval $(ssh-agent -s)"
  - 'ssh-add <(echo "$DEPLOY_PRODUCTION_SSH_PRIVATE_KEY")'
  - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  - 'echo -e "[wahay.app]:${SSH_PORT},[185.108.76.87]:${SSH_PORT} ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBD7qdL4lFlIQwRU2h2fV6oIMBZl1ifd6bbcajd8iRYaFQfVvj7qxGvorfaBETyquGe+lk0xw3NrcJCfK1LvT2Wo=" >> ~/.ssh/known_hosts'
  - chmod 644 ~/.ssh/known_hosts
  - 'echo "$GPG_SIGNING_SUBKEY" | gpg --batch --import'
  environment:
    name: production
    url: https://wahay.app
  when: manual
  only:
    - main
  script:
   - 'export DEPLOY_DIR=/home/wahay/tmp/deploy_binaries'
   - '$DO_SSH mkdir -p $DEPLOY_DIR'
   - '$DO_SSH rm -rf $DEPLOY_DIR/*'
   - 'export BINARY_NAME=$(find bin -name "wahay-*" | head -1)'
   - 'sha256sum  $BINARY_NAME > $BINARY_NAME.sha256sum'
   - 'gpg --batch --detach-sign --armor -u 3EE89711B35F8B3089646FCBF3B1159FC97D5490 $BINARY_NAME.sha256sum'
   - 'scp -P${SSH_PORT} $BINARY_NAME* wahay@wahay.app:$DEPLOY_DIR/'
   - 'scp -P${SSH_PORT} deployment/*sh wahay@wahay.app:bin/'
   - 'scp -P${SSH_PORT} deployment/*rb wahay@wahay.app:bin/'
   - 'scp -P${SSH_PORT} deployment/*html wahay@wahay.app:bin/'
   - '$DO_SSH chmod +x bin/*sh'
   - deployment/create-bundles.sh
   - 'scp -P${SSH_PORT} publish-bundles/* wahay@wahay.app:$DEPLOY_DIR/'
   - deployment/create-linux-packages.sh
   - 'scp -P${SSH_PORT} publish-linux-packages/* wahay@wahay.app:$DEPLOY_DIR/'
   - '$DO_SSH bin/publish-downloads.sh'
   - 'scp -P${SSH_PORT} deployment/supported-*-distros.txt wahay@wahay.app:$DEPLOY_DIR'
